version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  app:
    build:
      context: ./project
    image: transcript-rag-app
    container_name: transcript-rag-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - postgres
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - POSTGRES_DB=memmory_agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=150402
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./project:/project
      - ./uploads:/app/uploads
    working_dir: /project
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: memmory_agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150402
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  ollama_data:
  postgres_data:
